services:
  php:
    image: dunglas/frankenphp:latest-php8.3
    container_name: jobsniper_php
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      SERVER_NAME: ':80'
      FRANKENPHP_CONFIG: 'worker ./public/index.php'

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: jobsniper_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: jobsniper_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - database

volumes:
  db_data:
